options:
  concurrency: 0 # Use all CPUs

packages:
  api:
    cwd: build
    output: ../dist/entando-webui-core-api.zip
    trace:
      - src/index.js
      - src/app
    include:
      - ../package.json
      - ../**/*.hbs
