options:
  concurrency: 0 # Use all CPUs

packages:
  api:
    cwd: build
    output: ../dist/app-management-service.zip
    trace:
      - src/index.js
      - src/api
    include:
      - ../package.json
      - ../**/*.hbs
